//! Tiny control service (127.0.0.1, random port) — the sidecar's push channel
//! into the shell, plus the shell's own static pages (splash / error).
//! Endpoints (all require `Authorization: Bearer <token>` unless noted):
//!
//!   POST /ping            — sidecar heartbeat (anti-orphan liveness)
//!   POST /update-install  — {path}: spawn installer detached, then exit
//!   POST /show-window     — {kind, html, width, height}: show a dialog window
//!   POST /close-window    — {kind}: close a dialog window
//!   POST /restart-service — ask the shell to restart the sidecar
//!   POST /quit-app        — exit the shell
//!   POST /restart-app     — relaunch the shell
//!   POST /_desktop/boot-settled — WebUI boot chain settled inside the
//!                                 hidden main window (token via header or
//!                                 ?token= query — the no-cors fetch from
//!                                 boot-watch.js cannot set a header)
//!   GET  /pages/:page     — embedded shell pages (splash.html, error.html;
//!                           no auth — they are loaded by the shell's own
//!                           webview windows)
//!
//! tiny_http is used rather than axum: four fixed endpoints, blocking IO on a
//! plain thread, no extra dependency weight for a first Tauri build.

use serde::Deserialize;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicU16, Ordering};
use std::sync::{LazyLock, Mutex};
use tauri::{AppHandle, Manager};

use std::sync::Arc;

use crate::sidecar::{SidecarState, StatusKind};

/// Bound port of the shell control service (0 until started). Also consumed
/// by the window code to build splash/error page URLs.
pub static CTL_PORT: AtomicU16 = AtomicU16::new(0);

/// Control token, generated once per shell run and shared with the sidecar.
static CTL_TOKEN: LazyLock<Mutex<Option<String>>> = LazyLock::new(|| Mutex::new(None));

/// Generate the control token, start the control server and record the port.
/// Called synchronously from setup (before any shell window is created) so
/// the splash can load from this server; `sidecar::init` reuses the result.
pub fn init(app: AppHandle) -> (String, u16) {
    let token = uuid::Uuid::new_v4().to_string();
    let port = start(app, token.clone());
    *CTL_TOKEN.lock().unwrap() = Some(token.clone());
    (token, port)
}

pub fn port() -> u16 {
    CTL_PORT.load(Ordering::SeqCst)
}

pub fn token() -> Option<String> {
    CTL_TOKEN.lock().unwrap().clone()
}

#[derive(Deserialize)]
struct UpdateInstallBody {
    path: String,
}

/// Heartbeat body: the sidecar reports the control API port it actually
/// bound, so the shell can track it even if the reserved port shifted.
#[derive(Deserialize)]
struct PingBody {
    #[serde(rename = "controlPort")]
    control_port: u16,
}

#[derive(Deserialize)]
struct ShowWindowBody {
    kind: String,
    width: u32,
    height: u32,
    #[serde(default = "default_true")]
    dark: bool,
}

#[derive(Deserialize)]
struct CloseWindowBody {
    kind: String,
}

#[derive(Deserialize)]
struct OpenExternalBody {
    url: String,
}

fn default_true() -> bool {
    true
}

/// Start the control server on a random 127.0.0.1 port; returns the bound port.
/// The token is generated by the caller and handed to the sidecar via env.
pub fn start(app: AppHandle, token: String) -> u16 {
    let server = match tiny_http::Server::http("127.0.0.1:0") {
        Ok(s) => s,
        Err(e) => {
            log::error!("ctl_server: failed to bind: {e}");
            return 0;
        }
    };
    let port = match server.server_addr().to_ip() {
        Some(addr) => addr.port(),
        None => {
            log::error!("ctl_server: address not an IP");
            return 0;
        }
    };
    CTL_PORT.store(port, Ordering::SeqCst);

    std::thread::spawn(move || {
        for mut request in server.incoming_requests() {
            let url = request.url().to_string();
            let method = request.method().clone();
            // Shell pages (splash / error) are loaded by our own webview
            // windows, which cannot send an Authorization header on
            // navigation — exempt GET /pages/* from the token check.
            let (path, query) = url.split_once('?').unwrap_or((url.as_str(), ""));
            let is_page = method == tiny_http::Method::Get
                && path.starts_with("/pages/");
            let header_authorized = request
                .headers()
                .iter()
                .find(|h| h.field.as_str().as_str().eq_ignore_ascii_case("authorization"))
                .map(|h| h.value.as_str().trim().to_string())
                .map(|v| v == format!("Bearer {token}"))
                .unwrap_or(false);
            // The WebUI's boot-watch init script runs on the dsh origin
            // (127.0.0.1:<server_port>) and signals boot-settled with a
            // no-cors POST — no preflight, and no-cors forbids setting an
            // Authorization header, so THIS endpoint also accepts the token
            // as a query parameter (same pattern as the sidecar control
            // API's EventSource ?token=). No other route gets the fallback.
            let query_authorized = path == "/_desktop/boot-settled"
                && query.split('&').any(|kv| {
                    let mut it = kv.splitn(2, '=');
                    matches!(
                        (it.next(), it.next()),
                        (Some("token"), Some(t)) if t == token
                    )
                });
            let authorized = header_authorized || query_authorized;

            if !is_page && !authorized {
                let _ = request.respond(
                    tiny_http::Response::from_string("unauthorized")
                        .with_status_code(401),
                );
                continue;
            }

            let mut body = String::new();
            if method == tiny_http::Method::Post {
                // Read up to 1MB (take() needs Sized; the reader is a trait
                // object, so read manually with a cap).
                let mut buf = [0u8; 8192];
                let mut total = 0usize;
                let mut reader = request.as_reader();
                loop {
                    match std::io::Read::read(&mut reader, &mut buf) {
                        Ok(0) => break,
                        Ok(n) => {
                            total += n;
                            if total > (1 << 20) {
                                break;
                            }
                            body.push_str(&String::from_utf8_lossy(&buf[..n]));
                        }
                        Err(_) => break,
                    }
                }
            }

            let response = handle(&app, &url, &body);
            let _ = request.respond(response);
        }
    });

    log::info!("ctl_server: listening on 127.0.0.1:{port}");
    port
}

fn handle(app: &AppHandle, url: &str, body: &str) -> tiny_http::Response<std::io::Cursor<Vec<u8>>> {
    let ok = |text: &str| {
        tiny_http::Response::from_string(text.to_string())
            .with_status_code(200)
    };
    let html = |text: &str| {
        tiny_http::Response::from_string(text.to_string())
            .with_status_code(200)
            .with_header(
                "Content-Type: text/html; charset=utf-8"
                    .parse::<tiny_http::Header>()
                    .expect("static header"),
            )
    };

    let (path, _query) = url.split_once('?').unwrap_or((url, ""));

    match path {
        // Embedded shell pages (see module docs). include_str! keeps them in
        // the binary, so splash/error work even when the sidecar or dsh is
        // down — which is exactly when the error window appears.
        "/pages/splash.html" => html(include_str!("../pages/splash.html")),
        "/pages/error.html" => html(include_str!("../pages/error.html")),
        "/pages/about.html" => html(include_str!("../pages/about.html")),
        "/_desktop/boot-settled" => {
            // The WebUI's boot chain settled (or failed loudly) inside the
            // hidden main window — swap splash → real UI now, so the user
            // only ever sees one loading screen (the shell splash). Sent by
            // boot-watch.js; the fail-safe watchdog lives in windows.rs
            // (arm_boot_watchdog).
            let app2 = app.clone();
            let _ = app.run_on_main_thread(move || {
                crate::windows::show_main_window(&app2);
            });
            ok("revealed")
        }
        "/ping" => {
            // Keep the shell's view of the control API port in sync: the
            // sidecar may have re-bound elsewhere (reserved-port race).
            if let Ok(b) = serde_json::from_str::<PingBody>(body) {
                if b.control_port != 0 {
                    let state = app.state::<Arc<SidecarState>>();
                    state.sidecar_api_port.store(b.control_port, std::sync::atomic::Ordering::SeqCst);
                }
            }
            ok("pong")
        }
        "/dsh-auth" => {
            // Sidecar pushes the DSH launch token + cookie after parsing
            // `dsh web: http://...?token=` and doing the 303 exchange.
            if let Ok(auth) = serde_json::from_str::<crate::sidecar::DshAuthInfo>(body) {
                if !auth.cookie.is_empty() {
                    if let Some(state) = app.try_state::<Arc<SidecarState>>() {
                        let needs_reload = state
                            .dsh_auth
                            .try_read()
                            .map(|g| g.is_none())
                            .unwrap_or(false);
                        if let Ok(mut guard) = state.dsh_auth.try_write() {
                            *guard = Some(auth);
                        }
                        // First auth for this shell lifetime: the main window
                        // may already have navigated to the bare URL (401).
                        // Flag a reload once the health probe confirms the
                        // new engine is ready — health_loop handles it.
                        if needs_reload {
                            state
                                .reload_main_on_recover
                                .store(true, std::sync::atomic::Ordering::SeqCst);
                        }
                    }
                }
            }
            ok("ok")
        }
        "/update-install" => {
            match serde_json::from_str::<UpdateInstallBody>(body) {
                Ok(b) => {
                    let result = spawn_detached_installer(&b.path);
                    match result {
                        Ok(_) => {
                            log::info!("ctl_server: installer spawned, exiting");
                            app.exit(0);
                            ok("installer spawned")
                        }
                        Err(e) => {
                            log::error!("ctl_server: spawn installer failed: {e}");
                            tiny_http::Response::from_string(format!("spawn failed: {e}"))
                                .with_status_code(500)
                        }
                    }
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/show-window" => {
            match serde_json::from_str::<ShowWindowBody>(body) {
                Ok(b) => {
                    log::info!("ctl_server: /show-window kind={} {}x{}", b.kind, b.width, b.height);
                    let app2 = app.clone();
                    let _ = app.run_on_main_thread(move || {
                        // HTML lives in the sidecar's control server
                        // (/updater/page cache); the window loads it by URL.
                        let result = crate::windows::show_dialog_window(
                            &app2,
                            &b.kind,
                            b.width,
                            b.height,
                            b.dark,
                        );
                        if let Err(e) = result {
                            log::error!("ctl_server: show_dialog_window({}) failed: {e}", b.kind);
                        }
                    });
                    ok("window shown")
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/close-window" => {
            match serde_json::from_str::<CloseWindowBody>(body) {
                Ok(b) => {
                    log::info!("ctl_server: /close-window kind={}", b.kind);
                    let app2 = app.clone();
                    let _ = app.run_on_main_thread(move || {
                        crate::windows::close_dialog_window(&app2, &b.kind);
                    });
                    ok("window closed")
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/open-log-dir" => {
            // About dialog action: open the desktop (shell/sidecar) log dir.
            // The page is same-origin with this control service, so it calls
            // here directly with the Bearer token.
            let app2 = app.clone();
            let _ = app.run_on_main_thread(move || {
                let log_dir = crate::config::ShellConfig::load(&app2).log_dir;
                crate::tray::open_path(&app2, &log_dir);
            });
            ok("opened")
        }
        "/open-external" => {
            // About-dialog commit link / updater "GitHub Release" button:
            // open a URL in the system browser. Only http(s) is accepted —
            // the endpoint is token-protected but the payload originates in
            // WebView pages, so don't hand the opener arbitrary schemes.
            match serde_json::from_str::<OpenExternalBody>(body) {
                Ok(b) if b.url.starts_with("https://") || b.url.starts_with("http://") => {
                    let app2 = app.clone();
                    let _ = app.run_on_main_thread(move || {
                        let _ = tauri_plugin_opener::OpenerExt::opener(&app2)
                            .open_url(b.url, None::<&str>);
                    });
                    ok("opened")
                }
                Ok(_) => {
                    tiny_http::Response::from_string("bad url").with_status_code(400)
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/engine-swap-begin" => {
            // Engine swap (engine-updater.ts install flow): the sidecar is
            // about to kill dsh, swap the engine closure dirs and respawn —
            // the health loop would read the downtime as failures and pop
            // the error window. Flip the status to Starting (fresh 60s
            // startup window measured from now, exactly like sidecar::restart)
            // and flag the main window for reload once the new engine
            // answers. The sidecar process itself is untouched.
            let app2 = app.clone();
            let port = crate::config::ShellConfig::load(&app).server_port;
            tauri::async_runtime::spawn(async move {
                let state = app2.state::<Arc<SidecarState>>().clone();
                state.mark_starting(port).await;
            });
            let state = app.state::<Arc<SidecarState>>().clone();
            state
                .reload_main_on_recover
                .store(true, std::sync::atomic::Ordering::SeqCst);
            ok("starting")
        }
        "/restart-service" => {
            // Error-window "Restart Service" button: same entry point as the
            // tray menu (sidecar::restart).
            // The plugin-manager window URL pins the current sidecar control
            // port, which changes on restart — close the window here (the
            // page's own "Restart Service" button hits this route) instead of
            // leaving it stuck against the dead port. The main window reloads
            // itself once the service recovers (reload_main_on_recover).
            let app2 = app.clone();
            let _ = app.run_on_main_thread(move || {
                crate::windows::close_dialog_window(&app2, "plugins");
            });
            let state = app.state::<Arc<SidecarState>>();
            let snapshot = crate::sidecar::take_snapshot(&state);
            if snapshot.kind != StatusKind::Stopped {
                crate::sidecar::restart(&app.clone());
            }
            ok("restarting")
        }
        "/quit-app" => {
            let app2 = app.clone();
            tauri::async_runtime::spawn(async move {
                let _ = crate::sidecar::shutdown(&app2).await;
                app2.exit(0);
            });
            ok("quitting")
        }
        "/restart-app" => {
            let exe = std::env::current_exe();
            match exe {
                Ok(exe) => {
                    // Kill the sidecar first so the relaunched shell owns a fresh one.
                    let state = app.state::<Arc<SidecarState>>();
                    let snapshot = crate::sidecar::take_snapshot(&state);
                    if snapshot.kind != StatusKind::Stopped {
                        let handle = app.clone();
                        tauri::async_runtime::spawn(async move {
                            let _ = crate::sidecar::shutdown(&handle).await;
                        });
                    }
                    let _ = Command::new(exe).spawn();
                    app.exit(0);
                    ok("restarting")
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("no exe: {e}"))
                        .with_status_code(500)
                }
            }
        }
        _ => tiny_http::Response::from_string("not found").with_status_code(404),
    }
}

/// Spawn the installer fully detached from the shell's process tree, so the
/// shell's own exit / taskkill cleanup cannot take it down mid-install.
#[cfg(windows)]
fn spawn_detached_installer(path: &str) -> std::io::Result<()> {
    use std::os::windows::process::CommandExt;

    const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
    const DETACHED_PROCESS: u32 = 0x0000_0008;

    Command::new(path)
        .arg("--updated")
        .creation_flags(CREATE_NEW_PROCESS_GROUP | DETACHED_PROCESS)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;
    Ok(())
}

#[cfg(not(windows))]
fn spawn_detached_installer(path: &str) -> std::io::Result<()> {
    Command::new(path)
        .arg("--updated")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;
    Ok(())
}
